spring:
    datasource:
      url: jdbc:mysql://localhost:3306/shiro?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 6200581
      driver-class-name: com.mysql.jdbc.Driver
mybatis: #必要的,扫描xml文件
  cn.mapper-locations: Mapper/*.xml